Viewing DATA

In [2]:
import pandas as pd
csv_1=pd.read_csv("C:\\Users\\Local.Admin\\Desktop\\Python programs\\Pandas\\student_performance_dataset.csv",nrows=21)
csv_1

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
0,1,Male,11.0,98.0,9.5,Bachelors,Available,Yes,No,76.9,100.0,A,10.5,16.666667,20.5,Yes,High,87.9,Pass
1,2,Female,13.3,100.0,8.7,High School,Available,Yes,Active,75.5,100.0,A,12.0,26.250000,22.0,Yes,High,88.8,Pass
2,3,Male,11.9,85.3,10.9,Bachelors,Available,No,Active,88.5,97.3,A,12.8,20.416667,22.8,Yes,High,100.4,Pass
3,4,Male,9.6,77.5,11.0,NaN,Available,Yes,No,85.1,83.8,B,10.6,10.833333,20.6,Yes,High,94.7,Pass
4,5,Male,9.2,89.6,7.6,Bachelors,Available,No,Active,61.8,68.3,D,6.8,9.166667,16.8,Yes,High,71.0,Pass
5,6,Female,11.2,78.2,8.7,High School,Available,No,No,79.8,81.6,B,9.9,17.500000,19.9,Yes,High,91.0,Pass
6,7,Male,8.5,100.0,8.0,High School,Available,Yes,Active,58.6,69.6,D,6.5,6.250000,16.5,Yes,High,67.1,Pass
7,8,Male,13.2,86.4,9.0,High School,Available,Yes,No,78.4,88.0,B,12.2,25.833333,22.2,Yes,High,91.6,Pass
8,9,Male,12.3,81.3,9.7,Bachelors,Available,No,No,63.8,84.4,B,12.0,22.083333,22.0,Yes,High,76.1,Pass
9,10,Female,9.8,86.8,8.1,Bachelors,Available,Yes,No,57.7,74.3,C,7.9,11.666667,17.9,Yes,High,67.5,Pass
10,11,Male,7.9,71.5,8.7,High School,Available,No,Active,73.4,68.9,D,6.6,3.750000,16.6,No,High,81.3,Pass
11,12,Male,12.5,75.3,8.6,NaN,Available,Yes,No,37.9,76.7,C,11.1,22.916667,21.1,Yes,High,50.4,Pass
12,13,Male,10.3,97.0,10.0,Masters,Available,Yes,Active,49.0,82.6,B,10.3,13.750000,20.3,Yes,High,59.3,Pass
13,14,Male,12.4,78.4,9.9,Bachelors,Not Available,No,No,67.9,93.3,A,12.3,22.500000,22.3,Yes,High,80.3,Pass
14,15,Female,8.1,74.5,8.9,Masters,Available,Yes,Active,71.0,73.9,C,7.0,4.583333,17.0,No,High,79.1,Pass
15,16,Male,9.6,90.4,10.0,High School,Available,Yes,No,65.6,84.8,B,9.6,10.833333,19.6,Yes,High,75.2,Pass
16,17,Female,10.5,96.9,9.1,Bachelors,Available,Yes,No,51.0,81.5,B,9.6,14.583333,19.6,Yes,High,61.5,Pass
17,18,Female,10.6,92.2,9.5,Bachelors,Available,Yes,Active,60.2,75.5,C,10.1,15.000000,20.1,Yes,High,70.8,Pass
18,19,Female,9.8,95.0,11.8,Masters,Not Available,Yes,No,74.7,89.7,B,11.6,11.666667,21.6,Yes,High,84.5,Pass
19,20,Male,11.4,77.4,11.4,Masters,Not Available,No,Active,77.0,92.8,A,12.8,18.333333,22.8,Yes,High,88.4,Pass
20,21,Female,8.9,70.8,8.2,High School,Available,Yes,No,69.8,73.5,C,7.1,7.916667,17.1,No,High,78.7,Pass

In [3]:
csv_1.head()

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
0,1,Male,11.0,98.0,9.5,Bachelors,Available,Yes,No,76.9,100.0,A,10.5,16.666667,20.5,Yes,High,87.9,Pass
1,2,Female,13.3,100.0,8.7,High School,Available,Yes,Active,75.5,100.0,A,12.0,26.250000,22.0,Yes,High,88.8,Pass
2,3,Male,11.9,85.3,10.9,Bachelors,Available,No,Active,88.5,97.3,A,12.8,20.416667,22.8,Yes,High,100.4,Pass
3,4,Male,9.6,77.5,11.0,NaN,Available,Yes,No,85.1,83.8,B,10.6,10.833333,20.6,Yes,High,94.7,Pass
4,5,Male,9.2,89.6,7.6,Bachelors,Available,No,Active,61.8,68.3,D,6.8,9.166667,16.8,Yes,High,71.0,Pass

In [4]:
csv_1.tail(10)
csv_1.info()
csv_1.describe()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  21 non-null     int64
 1   gender                      21 non-null     str
 2   study_time_hours            21 non-null     float64
 3   attendance_percent          21 non-null     float64
 4   sleep_hours                 21 non-null     float64
 5   parental_education          19 non-null     str
 6   internet_access             21 non-null     str
 7   extracurricular_activities  21 non-null     str
 8   part_time_job               21 non-null     str
 9   previous_grade              21 non-null     float64
 10  final_exam_score            21 non-null     float64
 11  final_grade                 21 non-null     str
 12  total_study_sleep           21 non-null     float64
 13  study_percentage            21 non-null     float64
 14  total_hours                 21 non-null     float64
 15  good_attendence             21 non-null     str
 16  study_level                 21 non-null     str
 17  total_score                 21 non-null     float64
 18  pass_status                 21 non-null     str
dtypes: float64(9), int64(1), str(9)
memory usage: 3.2 KB

,student_id,study_time_hours,attendance_percent,sleep_hours,previous_grade,final_exam_score,total_study_sleep,study_percentage,total_hours,total_score
count,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000
mean,11.000000,10.571429,85.833333,9.395238,67.790476,82.880952,9.966667,14.880952,19.966667,78.361905
std,6.204837,1.624852,9.755016,1.153029,12.520060,10.008927,2.173323,6.770215,2.173323,12.727626
min,1.000000,7.900000,70.800000,7.600000,37.900000,68.300000,6.500000,3.750000,16.500000,50.400000
25%,6.000000,9.600000,77.500000,8.700000,60.200000,74.300000,7.900000,10.833333,17.900000,70.800000
50%,11.000000,10.500000,86.400000,9.100000,69.800000,82.600000,10.300000,14.583333,20.300000,79.100000
75%,16.000000,11.900000,95.000000,10.000000,76.900000,89.700000,12.000000,20.416667,22.000000,88.400000
max,21.000000,13.300000,100.000000,11.800000,88.500000,100.000000,12.800000,26.250000,22.800000,100.400000

In [5]:
# Attributes and properties
csv_1.shape
csv_1.columns
# csv_1.index

Index(['student_id', 'gender', 'study_time_hours', 'attendance_percent',
       'sleep_hours', 'parental_education', 'internet_access',
       'extracurricular_activities', 'part_time_job', 'previous_grade',
       'final_exam_score', 'final_grade', 'total_study_sleep',
       'study_percentage', 'total_hours', 'good_attendence', 'study_level',
       'total_score', 'pass_status'],
      dtype='str')

2.SELECTING DATA

In [6]:
csv_1["student_id"]#single column
csv_1[["student_id","gender"]]#multiple columns

    student_id  gender
0            1    Male
1            2  Female
2            3    Male
3            4    Male
4            5    Male
5            6  Female
6            7    Male
7            8    Male
8            9    Male
9           10  Female
10          11    Male
11          12    Male
12          13    Male
13          14    Male
14          15  Female
15          16    Male
16          17  Female
17          18  Female
18          19  Female
19          20    Male
20          21  Female

In [7]:
csv_1.loc[0]#selecting single row with all columns
csv_1.loc[1:5]#selecting range of rows with all columns
csv_1.loc[1:5:2]# selects rows based on step value

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
1,2,Female,13.3,100.0,8.7,High School,Available,Yes,Active,75.5,100.0,A,12.0,26.250000,22.0,Yes,High,88.8,Pass
3,4,Male,9.6,77.5,11.0,NaN,Available,Yes,No,85.1,83.8,B,10.6,10.833333,20.6,Yes,High,94.7,Pass
5,6,Female,11.2,78.2,8.7,High School,Available,No,No,79.8,81.6,B,9.9,17.500000,19.9,Yes,High,91.0,Pass

In [8]:
csv_1.iloc[4]#selecting single row with all columns
csv_1.iloc[1:5]#selecting range of rows with all columns
csv_1.iloc[1:5:2]# selects rows based on step value

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
1,2,Female,13.3,100.0,8.7,High School,Available,Yes,Active,75.5,100.0,A,12.0,26.250000,22.0,Yes,High,88.8,Pass
3,4,Male,9.6,77.5,11.0,NaN,Available,Yes,No,85.1,83.8,B,10.6,10.833333,20.6,Yes,High,94.7,Pass

3.FILTERING DATA

In [9]:
csv_1

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
0,1,Male,11.0,98.0,9.5,Bachelors,Available,Yes,No,76.9,100.0,A,10.5,16.666667,20.5,Yes,High,87.9,Pass
1,2,Female,13.3,100.0,8.7,High School,Available,Yes,Active,75.5,100.0,A,12.0,26.250000,22.0,Yes,High,88.8,Pass
2,3,Male,11.9,85.3,10.9,Bachelors,Available,No,Active,88.5,97.3,A,12.8,20.416667,22.8,Yes,High,100.4,Pass
3,4,Male,9.6,77.5,11.0,NaN,Available,Yes,No,85.1,83.8,B,10.6,10.833333,20.6,Yes,High,94.7,Pass
4,5,Male,9.2,89.6,7.6,Bachelors,Available,No,Active,61.8,68.3,D,6.8,9.166667,16.8,Yes,High,71.0,Pass
5,6,Female,11.2,78.2,8.7,High School,Available,No,No,79.8,81.6,B,9.9,17.500000,19.9,Yes,High,91.0,Pass
6,7,Male,8.5,100.0,8.0,High School,Available,Yes,Active,58.6,69.6,D,6.5,6.250000,16.5,Yes,High,67.1,Pass
7,8,Male,13.2,86.4,9.0,High School,Available,Yes,No,78.4,88.0,B,12.2,25.833333,22.2,Yes,High,91.6,Pass
8,9,Male,12.3,81.3,9.7,Bachelors,Available,No,No,63.8,84.4,B,12.0,22.083333,22.0,Yes,High,76.1,Pass
9,10,Female,9.8,86.8,8.1,Bachelors,Available,Yes,No,57.7,74.3,C,7.9,11.666667,17.9,Yes,High,67.5,Pass
10,11,Male,7.9,71.5,8.7,High School,Available,No,Active,73.4,68.9,D,6.6,3.750000,16.6,No,High,81.3,Pass
11,12,Male,12.5,75.3,8.6,NaN,Available,Yes,No,37.9,76.7,C,11.1,22.916667,21.1,Yes,High,50.4,Pass
12,13,Male,10.3,97.0,10.0,Masters,Available,Yes,Active,49.0,82.6,B,10.3,13.750000,20.3,Yes,High,59.3,Pass
13,14,Male,12.4,78.4,9.9,Bachelors,Not Available,No,No,67.9,93.3,A,12.3,22.500000,22.3,Yes,High,80.3,Pass
14,15,Female,8.1,74.5,8.9,Masters,Available,Yes,Active,71.0,73.9,C,7.0,4.583333,17.0,No,High,79.1,Pass
15,16,Male,9.6,90.4,10.0,High School,Available,Yes,No,65.6,84.8,B,9.6,10.833333,19.6,Yes,High,75.2,Pass
16,17,Female,10.5,96.9,9.1,Bachelors,Available,Yes,No,51.0,81.5,B,9.6,14.583333,19.6,Yes,High,61.5,Pass
17,18,Female,10.6,92.2,9.5,Bachelors,Available,Yes,Active,60.2,75.5,C,10.1,15.000000,20.1,Yes,High,70.8,Pass
18,19,Female,9.8,95.0,11.8,Masters,Not Available,Yes,No,74.7,89.7,B,11.6,11.666667,21.6,Yes,High,84.5,Pass
19,20,Male,11.4,77.4,11.4,Masters,Not Available,No,Active,77.0,92.8,A,12.8,18.333333,22.8,Yes,High,88.4,Pass
20,21,Female,8.9,70.8,8.2,High School,Available,Yes,No,69.8,73.5,C,7.1,7.916667,17.1,No,High,78.7,Pass

In [10]:
# Display students whose gender is Male.
csv_1[csv_1["gender"]=="Male"]
# Display students whose gender is Female.
csv_1.query("gender=='Female'")
# Display students whose study_time_hours is greater than 5.
csv_1[csv_1["study_time_hours"] > 3]
# Display students whose study_time_hours is less than 3.
csv_1.query("study_time_hours <3")
# Display students whose attendance_percent is greater than 90.
csv_1[csv_1["attendance_percent"] > 90]

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
0,1,Male,11.0,98.0,9.5,Bachelors,Available,Yes,No,76.9,100.0,A,10.5,16.666667,20.5,Yes,High,87.9,Pass
1,2,Female,13.3,100.0,8.7,High School,Available,Yes,Active,75.5,100.0,A,12.0,26.250000,22.0,Yes,High,88.8,Pass
6,7,Male,8.5,100.0,8.0,High School,Available,Yes,Active,58.6,69.6,D,6.5,6.250000,16.5,Yes,High,67.1,Pass
12,13,Male,10.3,97.0,10.0,Masters,Available,Yes,Active,49.0,82.6,B,10.3,13.750000,20.3,Yes,High,59.3,Pass
15,16,Male,9.6,90.4,10.0,High School,Available,Yes,No,65.6,84.8,B,9.6,10.833333,19.6,Yes,High,75.2,Pass
16,17,Female,10.5,96.9,9.1,Bachelors,Available,Yes,No,51.0,81.5,B,9.6,14.583333,19.6,Yes,High,61.5,Pass
17,18,Female,10.6,92.2,9.5,Bachelors,Available,Yes,Active,60.2,75.5,C,10.1,15.000000,20.1,Yes,High,70.8,Pass
18,19,Female,9.8,95.0,11.8,Masters,Not Available,Yes,No,74.7,89.7,B,11.6,11.666667,21.6,Yes,High,84.5,Pass

MULTI CONDITIONS

In [11]:
# Display students whose study_time_hours > 5 AND attendance_percent > 90.
csv_1[(csv_1["study_time_hours"] > 5) &(csv_1["attendance_percent"] > 90)]
# Display students whose study_time_hours > 5 OR attendance_percent > 90.
csv_1[(csv_1["study_time_hours"]>5) | (csv_1["attendance_percent"]>90)]
# Display Male students whose attendance is greater than 90.
csv_1.query("gender=='Male' and attendance_percent > 90")
# Display Female students whose study time is greater than 4.
csv_1.query("gender=='Female' and study_time_hours >4")
# Display students whose attendance_percent is between 80 and 90.
csv_1.query("80 <= attendance_percent <=90")
# Display students whose sleep_hours is between 6 and 8.
csv_1[(csv_1["sleep_hours"]>6) & (csv_1["sleep_hours"]<8)]

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
4,5,Male,9.2,89.6,7.6,Bachelors,Available,No,Active,61.8,68.3,D,6.8,9.166667,16.8,Yes,High,71.0,Pass

In [12]:
# Display students whose parental_education is "Bachelors".
csv_1[csv_1["parental_education"]=='Bachelors']
# Display students whose parental_education is "Masters".
csv_1.query("parental_education == 'Masters'")
# Display students who have internet_access = "Yes".
csv_1[csv_1["internet_access"]=='Yes']
# Display students who have part_time_job = "Yes".
csv_1.query("part_time_job == 'Yes'")
# Display students who have extracurricular_activities = "No".
csv_1[csv_1["extracurricular_activities"]=='No']

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
2,3,Male,11.9,85.3,10.9,Bachelors,Available,No,Active,88.5,97.3,A,12.8,20.416667,22.8,Yes,High,100.4,Pass
4,5,Male,9.2,89.6,7.6,Bachelors,Available,No,Active,61.8,68.3,D,6.8,9.166667,16.8,Yes,High,71.0,Pass
5,6,Female,11.2,78.2,8.7,High School,Available,No,No,79.8,81.6,B,9.9,17.500000,19.9,Yes,High,91.0,Pass
8,9,Male,12.3,81.3,9.7,Bachelors,Available,No,No,63.8,84.4,B,12.0,22.083333,22.0,Yes,High,76.1,Pass
10,11,Male,7.9,71.5,8.7,High School,Available,No,Active,73.4,68.9,D,6.6,3.750000,16.6,No,High,81.3,Pass
13,14,Male,12.4,78.4,9.9,Bachelors,Not Available,No,No,67.9,93.3,A,12.3,22.500000,22.3,Yes,High,80.3,Pass
19,20,Male,11.4,77.4,11.4,Masters,Not Available,No,Active,77.0,92.8,A,12.8,18.333333,22.8,Yes,High,88.4,Pass

In [13]:
# Display Female students who have internet access and attendance > 90.
csv_1.query("gender=='Female' and internet_access=='Yes' and attendance_percent > 90")
# Display students whose study time > 5 AND sleep hours < 7.
csv_1[(csv_1["study_time_hours"]>5) &(csv_1["sleep_hours"]<7)]
# Display students whose attendance > 90 OR study time > 6.
csv_1.query("attendance_percent >90 or study_time_hours >6")
# Display Male students whose study time is between 3 and 6.
csv_1[(csv_1["gender"]=='Male') & (csv_1["study_time_hours"]>=3) & (csv_1["study_time_hours"]<=6)]
# Display students who have Bachelors education AND internet access = Yes.
csv_1.query("parental_education=='Bachelors' and internet_access=='Yes'")
# Display students who do not have internet access.
csv_1[csv_1["internet_access"]=='No']

Empty DataFrame
Columns: [student_id, gender, study_time_hours, attendance_percent, sleep_hours, parental_education, internet_access, extracurricular_activities, part_time_job, previous_grade, final_exam_score, final_grade, total_study_sleep, study_percentage, total_hours, good_attendence, study_level, total_score, pass_status]
Index: []

In [14]:
csv_1[csv_1["parental_education"].isin(["Bachelors", "Masters"])]

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
0,1,Male,11.0,98.0,9.5,Bachelors,Available,Yes,No,76.9,100.0,A,10.5,16.666667,20.5,Yes,High,87.9,Pass
2,3,Male,11.9,85.3,10.9,Bachelors,Available,No,Active,88.5,97.3,A,12.8,20.416667,22.8,Yes,High,100.4,Pass
4,5,Male,9.2,89.6,7.6,Bachelors,Available,No,Active,61.8,68.3,D,6.8,9.166667,16.8,Yes,High,71.0,Pass
8,9,Male,12.3,81.3,9.7,Bachelors,Available,No,No,63.8,84.4,B,12.0,22.083333,22.0,Yes,High,76.1,Pass
9,10,Female,9.8,86.8,8.1,Bachelors,Available,Yes,No,57.7,74.3,C,7.9,11.666667,17.9,Yes,High,67.5,Pass
12,13,Male,10.3,97.0,10.0,Masters,Available,Yes,Active,49.0,82.6,B,10.3,13.750000,20.3,Yes,High,59.3,Pass
13,14,Male,12.4,78.4,9.9,Bachelors,Not Available,No,No,67.9,93.3,A,12.3,22.500000,22.3,Yes,High,80.3,Pass
14,15,Female,8.1,74.5,8.9,Masters,Available,Yes,Active,71.0,73.9,C,7.0,4.583333,17.0,No,High,79.1,Pass
16,17,Female,10.5,96.9,9.1,Bachelors,Available,Yes,No,51.0,81.5,B,9.6,14.583333,19.6,Yes,High,61.5,Pass
17,18,Female,10.6,92.2,9.5,Bachelors,Available,Yes,Active,60.2,75.5,C,10.1,15.000000,20.1,Yes,High,70.8,Pass
18,19,Female,9.8,95.0,11.8,Masters,Not Available,Yes,No,74.7,89.7,B,11.6,11.666667,21.6,Yes,High,84.5,Pass
19,20,Male,11.4,77.4,11.4,Masters,Not Available,No,Active,77.0,92.8,A,12.8,18.333333,22.8,Yes,High,88.4,Pass

1️⃣ isin() → Multiple Values

In [15]:
# Q1. Display students whose parental_education is Bachelors or Masters.
csv_1[csv_1["parental_education"].isin(["Bachelors","Masters"])]
# Q2. Display students whose parental_education is High School or Bachelors.
csv_1[csv_1["parental_education"].isin(["High School","Bachelors"])]
# Q3. Display students whose gender is Male or Female.
csv_1[csv_1["gender"].isin(["Male","Female"])]
# Q4. Display students whose internet_access is Yes or No.
csv_1[csv_1["internet_access"].isin(["Yes","No"])]
# Q5. Display students whose part_time_job is Yes or No.
csv_1[csv_1["part_time_job"].isin(["Yes","No"])]

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
0,1,Male,11.0,98.0,9.5,Bachelors,Available,Yes,No,76.9,100.0,A,10.5,16.666667,20.5,Yes,High,87.9,Pass
3,4,Male,9.6,77.5,11.0,NaN,Available,Yes,No,85.1,83.8,B,10.6,10.833333,20.6,Yes,High,94.7,Pass
5,6,Female,11.2,78.2,8.7,High School,Available,No,No,79.8,81.6,B,9.9,17.500000,19.9,Yes,High,91.0,Pass
7,8,Male,13.2,86.4,9.0,High School,Available,Yes,No,78.4,88.0,B,12.2,25.833333,22.2,Yes,High,91.6,Pass
8,9,Male,12.3,81.3,9.7,Bachelors,Available,No,No,63.8,84.4,B,12.0,22.083333,22.0,Yes,High,76.1,Pass
9,10,Female,9.8,86.8,8.1,Bachelors,Available,Yes,No,57.7,74.3,C,7.9,11.666667,17.9,Yes,High,67.5,Pass
11,12,Male,12.5,75.3,8.6,NaN,Available,Yes,No,37.9,76.7,C,11.1,22.916667,21.1,Yes,High,50.4,Pass
13,14,Male,12.4,78.4,9.9,Bachelors,Not Available,No,No,67.9,93.3,A,12.3,22.500000,22.3,Yes,High,80.3,Pass
15,16,Male,9.6,90.4,10.0,High School,Available,Yes,No,65.6,84.8,B,9.6,10.833333,19.6,Yes,High,75.2,Pass
16,17,Female,10.5,96.9,9.1,Bachelors,Available,Yes,No,51.0,81.5,B,9.6,14.583333,19.6,Yes,High,61.5,Pass
18,19,Female,9.8,95.0,11.8,Masters,Not Available,Yes,No,74.7,89.7,B,11.6,11.666667,21.6,Yes,High,84.5,Pass
20,21,Female,8.9,70.8,8.2,High School,Available,Yes,No,69.8,73.5,C,7.1,7.916667,17.1,No,High,78.7,Pass

2️⃣ between() → Range

In [16]:
# Q6. Display students whose study_time_hours is between 2 and 5.
csv_1[csv_1["study_time_hours"].between(2,5)]
# Q7. Display students whose attendance_percent is between 80 and 95.
csv_1[csv_1["attendance_percent"].between(80,95)]
# Q8. Display students whose sleep_hours is between 5 and 7.
csv_1[csv_1["sleep_hours"].between(5,7)]
# Q9. Display students whose study_time_hours is between 3 and 6.
csv_1[csv_1["study_time_hours"].between(3,6)]
# Q10. Display students whose attendance_percent is between 70 and 85.
csv_1[csv_1["attendance_percent"].between(70,85)]

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
3,4,Male,9.6,77.5,11.0,NaN,Available,Yes,No,85.1,83.8,B,10.6,10.833333,20.6,Yes,High,94.7,Pass
5,6,Female,11.2,78.2,8.7,High School,Available,No,No,79.8,81.6,B,9.9,17.500000,19.9,Yes,High,91.0,Pass
8,9,Male,12.3,81.3,9.7,Bachelors,Available,No,No,63.8,84.4,B,12.0,22.083333,22.0,Yes,High,76.1,Pass
10,11,Male,7.9,71.5,8.7,High School,Available,No,Active,73.4,68.9,D,6.6,3.750000,16.6,No,High,81.3,Pass
11,12,Male,12.5,75.3,8.6,NaN,Available,Yes,No,37.9,76.7,C,11.1,22.916667,21.1,Yes,High,50.4,Pass
13,14,Male,12.4,78.4,9.9,Bachelors,Not Available,No,No,67.9,93.3,A,12.3,22.500000,22.3,Yes,High,80.3,Pass
14,15,Female,8.1,74.5,8.9,Masters,Available,Yes,Active,71.0,73.9,C,7.0,4.583333,17.0,No,High,79.1,Pass
19,20,Male,11.4,77.4,11.4,Masters,Not Available,No,Active,77.0,92.8,A,12.8,18.333333,22.8,Yes,High,88.4,Pass
20,21,Female,8.9,70.8,8.2,High School,Available,Yes,No,69.8,73.5,C,7.1,7.916667,17.1,No,High,78.7,Pass

3️⃣ ~ → NOT / Exclude

In [17]:
# Q11. Display students who are NOT Male.
csv_1[~csv_1["gender"].isin(["Male"])]
# Q12. Display students who do NOT have internet access.
csv_1[~csv_1["internet_access"].isin(["Yes"])]
# Q13. Display students whose parental_education is NOT Bachelors.
csv_1[~csv_1["parental_education"].isin(["Bachelors"])]
# Q14. Display students whose part_time_job is NOT Yes.
csv_1[~csv_1["part_time_job"].isin(["Yes"])]
# Q15. Display students whose parental_education is NOT Bachelors or Masters.
csv_1[~csv_1["parental_education"].isin(["Bachelors","Masters"])]

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
1,2,Female,13.3,100.0,8.7,High School,Available,Yes,Active,75.5,100.0,A,12.0,26.250000,22.0,Yes,High,88.8,Pass
3,4,Male,9.6,77.5,11.0,NaN,Available,Yes,No,85.1,83.8,B,10.6,10.833333,20.6,Yes,High,94.7,Pass
5,6,Female,11.2,78.2,8.7,High School,Available,No,No,79.8,81.6,B,9.9,17.500000,19.9,Yes,High,91.0,Pass
6,7,Male,8.5,100.0,8.0,High School,Available,Yes,Active,58.6,69.6,D,6.5,6.250000,16.5,Yes,High,67.1,Pass
7,8,Male,13.2,86.4,9.0,High School,Available,Yes,No,78.4,88.0,B,12.2,25.833333,22.2,Yes,High,91.6,Pass
10,11,Male,7.9,71.5,8.7,High School,Available,No,Active,73.4,68.9,D,6.6,3.750000,16.6,No,High,81.3,Pass
11,12,Male,12.5,75.3,8.6,NaN,Available,Yes,No,37.9,76.7,C,11.1,22.916667,21.1,Yes,High,50.4,Pass
15,16,Male,9.6,90.4,10.0,High School,Available,Yes,No,65.6,84.8,B,9.6,10.833333,19.6,Yes,High,75.2,Pass
20,21,Female,8.9,70.8,8.2,High School,Available,Yes,No,69.8,73.5,C,7.1,7.916667,17.1,No,High,78.7,Pass

4️⃣ isna() → Missing Values

In [18]:
# Q16. Display students whose parental_education is missing.
csv_1[csv_1["parental_education"].isna()]
# Q17. Display students whose parental_education is missing AND internet_access is "Yes".
csv_1[(csv_1["parental_education"].isna()) & (csv_1["internet_access"]=='Yes')]
# Q18. Display students whose parental_education is missing AND gender is "Male".
csv_1[(csv_1["parental_education"].isna()) & (csv_1["gender"]=='Male')]
# Q19. Display students whose parental_education is missing AND attendance_percent > 80.
csv_1[(csv_1["parental_education"].isna()) & (csv_1["attendance_percent"]>80)]
# Q20. Display students whose parental_education is missing OR sleep_hours < 6.
csv_1[(csv_1["parental_education"].isna()) | (csv_1["sleep_hours"]<6)]

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
3,4,Male,9.6,77.5,11.0,NaN,Available,Yes,No,85.1,83.8,B,10.6,10.833333,20.6,Yes,High,94.7,Pass
11,12,Male,12.5,75.3,8.6,NaN,Available,Yes,No,37.9,76.7,C,11.1,22.916667,21.1,Yes,High,50.4,Pass

5️⃣ notna() → NOT Missing Values

In [19]:
# Q21. Display students whose parental_education is NOT missing.
csv_1[csv_1["parental_education"].notna()]
# Q22. Display students whose parental_education is NOT missing AND attendance_percent > 90.
csv_1[csv_1["parental_education"].notna() & (csv_1["attendance_percent"]>90)]
# Q23. Display students whose parental_education is NOT missing AND study_time_hours > 4.
csv_1[csv_1["parental_education"].notna() & (csv_1["study_time_hours"]>4)]
# Q24. Display students whose parental_education is NOT missing AND internet_access == "Yes".
csv_1[csv_1["parental_education"].notna() & (csv_1["internet_access"]=='Yes')]
# Q25. Display students whose parental_education is NOT missing OR attendance_percent < 75.
csv_1[csv_1["parental_education"].notna() | (csv_1["attendance_percent"]<75)]

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
0,1,Male,11.0,98.0,9.5,Bachelors,Available,Yes,No,76.9,100.0,A,10.5,16.666667,20.5,Yes,High,87.9,Pass
1,2,Female,13.3,100.0,8.7,High School,Available,Yes,Active,75.5,100.0,A,12.0,26.250000,22.0,Yes,High,88.8,Pass
2,3,Male,11.9,85.3,10.9,Bachelors,Available,No,Active,88.5,97.3,A,12.8,20.416667,22.8,Yes,High,100.4,Pass
4,5,Male,9.2,89.6,7.6,Bachelors,Available,No,Active,61.8,68.3,D,6.8,9.166667,16.8,Yes,High,71.0,Pass
5,6,Female,11.2,78.2,8.7,High School,Available,No,No,79.8,81.6,B,9.9,17.500000,19.9,Yes,High,91.0,Pass
6,7,Male,8.5,100.0,8.0,High School,Available,Yes,Active,58.6,69.6,D,6.5,6.250000,16.5,Yes,High,67.1,Pass
7,8,Male,13.2,86.4,9.0,High School,Available,Yes,No,78.4,88.0,B,12.2,25.833333,22.2,Yes,High,91.6,Pass
8,9,Male,12.3,81.3,9.7,Bachelors,Available,No,No,63.8,84.4,B,12.0,22.083333,22.0,Yes,High,76.1,Pass
9,10,Female,9.8,86.8,8.1,Bachelors,Available,Yes,No,57.7,74.3,C,7.9,11.666667,17.9,Yes,High,67.5,Pass
10,11,Male,7.9,71.5,8.7,High School,Available,No,Active,73.4,68.9,D,6.6,3.750000,16.6,No,High,81.3,Pass
12,13,Male,10.3,97.0,10.0,Masters,Available,Yes,Active,49.0,82.6,B,10.3,13.750000,20.3,Yes,High,59.3,Pass
13,14,Male,12.4,78.4,9.9,Bachelors,Not Available,No,No,67.9,93.3,A,12.3,22.500000,22.3,Yes,High,80.3,Pass
14,15,Female,8.1,74.5,8.9,Masters,Available,Yes,Active,71.0,73.9,C,7.0,4.583333,17.0,No,High,79.1,Pass
15,16,Male,9.6,90.4,10.0,High School,Available,Yes,No,65.6,84.8,B,9.6,10.833333,19.6,Yes,High,75.2,Pass
16,17,Female,10.5,96.9,9.1,Bachelors,Available,Yes,No,51.0,81.5,B,9.6,14.583333,19.6,Yes,High,61.5,Pass
17,18,Female,10.6,92.2,9.5,Bachelors,Available,Yes,Active,60.2,75.5,C,10.1,15.000000,20.1,Yes,High,70.8,Pass
18,19,Female,9.8,95.0,11.8,Masters,Not Available,Yes,No,74.7,89.7,B,11.6,11.666667,21.6,Yes,High,84.5,Pass
19,20,Male,11.4,77.4,11.4,Masters,Not Available,No,Active,77.0,92.8,A,12.8,18.333333,22.8,Yes,High,88.4,Pass
20,21,Female,8.9,70.8,8.2,High School,Available,Yes,No,69.8,73.5,C,7.1,7.916667,17.1,No,High,78.7,Pass

4.SORTING DATA

In [20]:
# Q1. Sort students by attendance_percent from smallest to largest.
csv_1.sort_values("attendance_percent",ascending=True)
# Q2. Sort students by attendance_percent from largest to smallest.
csv_1.sort_values("attendance_percent",ascending=False)
# Q3. Sort students by study_time_hours from smallest to largest.
csv_1.sort_values("study_time_hours",ascending=True)
# Q4. Sort students by study_time_hours from largest to smallest.
csv_1.sort_values("study_time_hours",ascending=False)
# Q5. Sort students by sleep_hours from smallest to largest.
csv_1.sort_values("sleep_hours",ascending=True)
# Q6. Sort students by gender and then by attendance_percent.
csv_1.sort_values(["gender","attendance_percent"])
# Q7. Sort students by gender ascending and attendance_percent descending.
csv_1.sort_values(["gender","attendance_percent"],
                  ascending=[True,False])
# Q8. Sort students by parental_education and then study_time_hours.
csv_1.sort_values(["parental_education","study_time_hours"])

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade,total_study_sleep,study_percentage,total_hours,good_attendence,study_level,total_score,pass_status
4,5,Male,9.2,89.6,7.6,Bachelors,Available,No,Active,61.8,68.3,D,6.8,9.166667,16.8,Yes,High,71.0,Pass
9,10,Female,9.8,86.8,8.1,Bachelors,Available,Yes,No,57.7,74.3,C,7.9,11.666667,17.9,Yes,High,67.5,Pass
16,17,Female,10.5,96.9,9.1,Bachelors,Available,Yes,No,51.0,81.5,B,9.6,14.583333,19.6,Yes,High,61.5,Pass
17,18,Female,10.6,92.2,9.5,Bachelors,Available,Yes,Active,60.2,75.5,C,10.1,15.000000,20.1,Yes,High,70.8,Pass
0,1,Male,11.0,98.0,9.5,Bachelors,Available,Yes,No,76.9,100.0,A,10.5,16.666667,20.5,Yes,High,87.9,Pass
2,3,Male,11.9,85.3,10.9,Bachelors,Available,No,Active,88.5,97.3,A,12.8,20.416667,22.8,Yes,High,100.4,Pass
8,9,Male,12.3,81.3,9.7,Bachelors,Available,No,No,63.8,84.4,B,12.0,22.083333,22.0,Yes,High,76.1,Pass
13,14,Male,12.4,78.4,9.9,Bachelors,Not Available,No,No,67.9,93.3,A,12.3,22.500000,22.3,Yes,High,80.3,Pass
10,11,Male,7.9,71.5,8.7,High School,Available,No,Active,73.4,68.9,D,6.6,3.750000,16.6,No,High,81.3,Pass
6,7,Male,8.5,100.0,8.0,High School,Available,Yes,Active,58.6,69.6,D,6.5,6.250000,16.5,Yes,High,67.1,Pass
20,21,Female,8.9,70.8,8.2,High School,Available,Yes,No,69.8,73.5,C,7.1,7.916667,17.1,No,High,78.7,Pass
15,16,Male,9.6,90.4,10.0,High School,Available,Yes,No,65.6,84.8,B,9.6,10.833333,19.6,Yes,High,75.2,Pass
5,6,Female,11.2,78.2,8.7,High School,Available,No,No,79.8,81.6,B,9.9,17.500000,19.9,Yes,High,91.0,Pass
7,8,Male,13.2,86.4,9.0,High School,Available,Yes,No,78.4,88.0,B,12.2,25.833333,22.2,Yes,High,91.6,Pass
1,2,Female,13.3,100.0,8.7,High School,Available,Yes,Active,75.5,100.0,A,12.0,26.250000,22.0,Yes,High,88.8,Pass
14,15,Female,8.1,74.5,8.9,Masters,Available,Yes,Active,71.0,73.9,C,7.0,4.583333,17.0,No,High,79.1,Pass
18,19,Female,9.8,95.0,11.8,Masters,Not Available,Yes,No,74.7,89.7,B,11.6,11.666667,21.6,Yes,High,84.5,Pass
12,13,Male,10.3,97.0,10.0,Masters,Available,Yes,Active,49.0,82.6,B,10.3,13.750000,20.3,Yes,High,59.3,Pass
19,20,Male,11.4,77.4,11.4,Masters,Not Available,No,Active,77.0,92.8,A,12.8,18.333333,22.8,Yes,High,88.4,Pass
3,4,Male,9.6,77.5,11.0,NaN,Available,Yes,No,85.1,83.8,B,10.6,10.833333,20.6,Yes,High,94.7,Pass
11,12,Male,12.5,75.3,8.6,NaN,Available,Yes,No,37.9,76.7,C,11.1,22.916667,21.1,Yes,High,50.4,Pass

5.Selecting Columns & Rows
   - df["column"]
   - df[["col1", "col2"]]
   - loc
   - iloc

In [21]:
# Select the first row using loc.
csv_1.loc[0]
# Select rows 2 to 5 using loc.
csv_1.loc[2:5]
# Select the student_name column using loc.
csv_1.loc[:,"gender"]
# Select student_name and marks columns using loc.
csv_1.loc[:,["gender","sleep_hours"]]
# Select rows 0 to 4 with columns student_name and marks using loc.
csv_1.loc[0:4,["gender","sleep_hours"]]
# Select the first row using iloc.
csv_1.iloc[0]
# Select rows at positions 2 to 5 using iloc.
csv_1.iloc[2:5]
# Select the third column using iloc.
csv_1.iloc[2]
# Select the first and third columns using iloc.
csv_1.iloc[:,0:3]
# Select the first 5 rows and first 3 columns using iloc.
# csv_1.iloc[0:5,0:3]

    student_id  gender  study_time_hours
0            1    Male              11.0
1            2  Female              13.3
2            3    Male              11.9
3            4    Male               9.6
4            5    Male               9.2
5            6  Female              11.2
6            7    Male               8.5
7            8    Male              13.2
8            9    Male              12.3
9           10  Female               9.8
10          11    Male               7.9
11          12    Male              12.5
12          13    Male              10.3
13          14    Male              12.4
14          15  Female               8.1
15          16    Male               9.6
16          17  Female              10.5
17          18  Female              10.6
18          19  Female               9.8
19          20    Male              11.4
20          21  Female               8.9

6. Adding & Modifying Columns

In [22]:
# # # 3. Adding & Modifying Columns

# # # A. Create a New Column

# # Q1. Create a new column called total_hours by adding study_time_hours and sleep_hours.
# csv_1["total_hours"]=csv_1["study_time_hours"]+csv_1["sleep_hours"]
# # Q2. Create a new column called good_attendance:
# #     - "Yes" if attendance_percent >= 75
# #     - "No" otherwise.
# import numpy as np
# csv_1["good_attendence"]=np.where(csv_1["attendance_percent"]>=75,"Yes","No")

# # Q3. Create a new column called study_level:
# #     - "High" if study_time_hours >= 5
# #     - "Low" otherwise.
# csv_1["study_level"]=np.where(csv_1["study_time_hours"]>=5,"High","Low")

# # Q4. Create a new column called total_score by adding final_exam_score and previous_grade.
# csv_1["total_score"]=csv_1["final_exam_score"]+csv_1["previous_grade"]

# # Q5. Create a new column called pass_status:
# #     - "Pass" if final_exam_score >= 40
# #     - "Fail" otherwise.
# csv_1["pass_status"]=np.where(csv_1["final_exam_score"]>=40,"Pass","Fail")

# # # B. Change Column Values

# # Q6. Change "Yes" to "Available" in the internet_access column.
# csv_1["internet_access"]=csv_1["internet_access"].replace({"Yes": "Available", "No": "Not Available"})
# # Q7. Change "No" to "Not Available" in the internet_access column.
# # csv_1["internet_access"].replace("No","Not Available",inplace=True)
# csv_1.to_csv("student_performance_dataset.csv",index=False)
# # Q8. Change "Yes" to "Active" in the part_time_job column.
# csv_1["part_time_job"]=csv_1["part_time_job"].replace("Yes","Active")

# # Q9. Increase all values in study_time_hours by 1.
# csv_1["study_time_hours"]=csv_1["study_time_hours"]+1
# # Q10. Increase all values in sleep_hours by 0.5.
# csv_1["sleep_hours"]=csv_1["sleep_hours"]+0.5


# # # C. Rename Columns

# # Q11. Rename gender to student_gender.
# csv_1=csv_1.rename(columns={"gender":"student_gender"})
# # Q12. Rename study_time_hours to study_hours.
# csv_1=csv_1.rename(columns={"study_time_hours":"study_hours"})
# # Q13. Rename sleep_hours to sleep_time.
# csv_1=csv_1.rename(columns={"sleep_hours":"sleep_time"})
# # Q14. Rename final_exam_score to exam_score.
# csv_1=csv_1.rename(columns={"final_exam_score":"exam_score"})
# # Q15. Rename previous_grade to prev_grade.
csv_1=csv_1.rename(columns={"previous_grade":"prev_grade"})

7. Handling Missing Data Through functions
   - fillna()
   - dropna()
   - replace()

In [23]:
import pandas as pd
csv_2=pd.read_csv("dirty_sales_data.csv")

In [29]:
csv_2.isna().sum()
csv_2.head(40)

,Order_ID,Customer_Name,Product_Category,Order_Date,Quantity,Price_Per_Item
0,ORD_1000,alice smith,Office Supplies,invalid_date,3.0,15.0
1,ORD_1001,BOB JONES,Office Supplies,2026/01/15,1.0,20.0
2,ORD_1002,Charlie Brown,Furniture,2026-01-15,500.0,15.0
3,ORD_1003,alice smith,Office Supplies,invalid_date,5.0,10.5
4,ORD_1004,david clear,Office Supplies,invalid_date,1.0,15.0
5,ORD_1005,User_0,electronics,15/01/2026,3.0,15.0
6,ORD_1006,User_1,Furniture,2026-01-15,2.0,15.0
8,ORD_1008,User_3,Furniture,2026/01/15,3.0,15.0
9,ORD_1009,User_4,Office Supplies,2026/01/15,500.0,15.0
10,ORD_1010,User_5,Office Supplies,15/01/2026,1.0,20.0
12,ORD_1012,User_7,Office Supplies,2026-01-15,1.0,15.0
13,ORD_1013,User_8,electronics,2026/01/15,500.0,20.0
14,ORD_1014,User_9,Office Supplies,invalid_date,1.0,15.0
15,ORD_1015,User_10,electronics,invalid_date,2.0,15.0
18,ORD_1018,User_13,Electronics,2026/01/15,500.0,15.0
19,ORD_1019,User_14,Office Supplies,2026-01-15,2.0,10.5
20,ORD_1020,User_15,electronics,2026/01/15,3.0,10.5
21,ORD_1021,User_16,Office Supplies,2026-01-15,1.0,20.0
22,ORD_1022,User_17,Office Supplies,2026/01/15,5.0,15.0
23,ORD_1023,User_18,Electronics,15/01/2026,1.0,20.0
24,ORD_1024,User_19,Electronics,2026/01/15,1.0,20.0
25,ORD_1025,User_20,Furniture,2026-01-15,3.0,20.0
26,ORD_1026,User_21,Furniture,2026-01-15,1.0,20.0
27,ORD_1027,User_22,electronics,15/01/2026,2.0,15.0
28,ORD_1028,User_23,Office Supplies,2026/01/15,2.0,15.0
30,ORD_1030,User_25,Furniture,15/01/2026,500.0,10.5
31,ORD_1031,User_26,Office Supplies,2026/01/15,5.0,15.0
32,ORD_1032,User_27,Office Supplies,2026/01/15,1.0,10.5
33,ORD_1033,User_28,Electronics,2026-01-15,1.0,15.0
34,ORD_1034,User_29,Furniture,2026/01/15,3.0,10.5
35,ORD_1035,User_30,Office Supplies,2026/01/15,500.0,20.0
36,ORD_1036,User_31,Furniture,15/01/2026,2.0,10.5
37,ORD_1037,User_32,Office Supplies,15/01/2026,5.0,15.0
39,ORD_1039,User_34,electronics,2026-01-15,2.0,15.0
40,ORD_1040,User_35,Office Supplies,2026/01/15,500.0,15.0
42,ORD_1042,User_37,Office Supplies,invalid_date,3.0,15.0
43,ORD_1043,User_38,electronics,2026/01/15,3.0,15.0
44,ORD_1044,User_39,electronics,2026-01-15,1.0,10.5
45,ORD_1045,User_40,Electronics,invalid_date,500.0,15.0
46,ORD_1046,User_41,electronics,2026-01-15,5.0,10.5

In [25]:
# Q1. Check the number of missing values in each column.
csv_2.isna().sum()
# Q2. Fill missing values in the Quantity column with 0.
csv_2["Quantity"].fillna(0)

# Q3. Fill missing values in the Price_Per_Item column with 0.
csv_2["Price_Per_Item"].fillna(0)

# Q4. Find the mean of Quantity and fill missing values with the mean.
# qun_mean=csv_2["Quantity"].mean()
# csv_2["Quantity"]=csv_2["Quantity"].fillna((round(qun_mean,0)))
# # print(round(qun_mean,0))

# Q5. Find the median of Price_Per_Item and fill missing values with the median.
csv_2["Price_Per_Item"]=csv_2["Price_Per_Item"].str.replace("$","",regex=False)
csv_2["Price_Per_Item"]=csv_2["Price_Per_Item"].astype(float)
ppi_median=csv_2["Price_Per_Item"].median()
# print(ppi_median)
csv_2["Price_Per_Item"]=csv_2["Price_Per_Item"].fillna(ppi_median)
# Q6. Fill missing values in Product_Category with "Unknown".
csv_2["Product_Category"]=csv_2["Product_Category"].fillna("Unknown")
# Q7. Fill missing values in Customer_Name with "Unknown".
csv_2["Customer_Name"]=csv_2["Customer_Name"].fillna("Unknown")

# Q8. Remove all rows that contain missing values.
csv_2.dropna(inplace=True)

# Q9. Remove rows where Quantity is missing.
csv_2.dropna(subset=["Quantity"],inplace=True)

# Q10. Remove rows where Price_Per_Item is missing.
csv_2.dropna(subset=["Price_Per_Item"],inplace=True)

# Q11. Remove columns that contain missing values.
csv_2.dropna(axis=1,inplace=True)
# Q12. Replace "unknown" with "Unknown".
csv_2.replace("unknown","Unknown",inplace=True)

# Q13. Replace empty/invalid category values with "Unknown".
csv_2.fillna("Unknown",inplace=True)

# Q14. Find any incorrect Product_Category value and replace it with the correct value.
csv_2["Product_Category"]=csv_2["Product_Category"].replace("Unknown","Office Supplies")
# Q15. Create a copy of df and handle missing values without changing the original df.
df_cleaned=csv_2.copy()
# Q16. Fill missing values:
# Quantity → mean
df_cleaned["Quantity"]=df_cleaned["Quantity"].fillna(df_cleaned["Quantity"].mean())
# Price_Per_Item → median
df_cleaned["Price_Per_Item"]=df_cleaned["Price_Per_Item"].fillna(df_cleaned["Price_Per_Item"].median())
# Product_Category → "Unknown"
df_cleaned["Product_Category"]=df_cleaned["Product_Category"].fillna("Unknown")

# Q17. Check again and verify that no missing values are left.
csv_2.isna().sum()
df_cleaned.isna().sum()

Order_ID            0
Customer_Name       0
Product_Category    0
Order_Date          0
Quantity            0
Price_Per_Item      0
dtype: int64

In [26]:
csv_2["Product_Category"].unique()
csv_2["Order_Date"].unique()

<StringArray>
['invalid_date', '2026/01/15', '2026-01-15', '15/01/2026']
Length: 4, dtype: str