In [2]:
import pandas as pd
csv_1=pd.read_csv("C:\\Users\\Local.Admin\\Desktop\\Python programs\\Pandas\\student_performance_dataset.csv",nrows=10)
csv_1

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
5,6,Female,4.2,78.2,5.7,High School,Yes,No,No,79.8,81.6,B
6,7,Male,1.5,100.0,5.0,High School,Yes,Yes,Yes,58.6,69.6,D
7,8,Male,6.2,86.4,6.0,High School,Yes,Yes,No,78.4,88.0,B
8,9,Male,5.3,81.3,6.7,Bachelors,Yes,No,No,63.8,84.4,B
9,10,Female,2.8,86.8,5.1,Bachelors,Yes,Yes,No,57.7,74.3,C

In [1]:
csv_1=pd.read_csv("C:\\Users\\Local.Admin\\Desktop\\Python programs\\Pandas\\student_performance_dataset.csv",usecols=[0,3])
csv_1

NameError: name 'pd' is not defined

In [4]:
csv_1=pd.read_csv("C:\\Users\\Local.Admin\\Desktop\\Python programs\\Pandas\\student_performance_dataset.csv",skiprows=[1,2,5])
csv_1

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
1,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
2,6,Female,4.2,78.2,5.7,High School,Yes,No,No,79.8,81.6,B
3,7,Male,1.5,100.0,5.0,High School,Yes,Yes,Yes,58.6,69.6,D
4,8,Male,6.2,86.4,6.0,High School,Yes,Yes,No,78.4,88.0,B
...,...,...,...,...,...,...,...,...,...,...,...,...
992,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
993,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
994,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
995,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
996,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [5]:
csv_1=pd.read_csv("C:\\Users\\Local.Admin\\Desktop\\Python programs\\Pandas\\student_performance_dataset.csv",index_col="student_id")
csv_1

,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
student_id,,,,,,,,,,,
1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...
996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [6]:
csv_1=pd.read_csv("C:\\Users\\Local.Admin\\Desktop\\Python programs\\Pandas\\student_performance_dataset.csv",header=99)
csv_1

       99  Female  2.4  87.2  6.1  High School  Yes Yes.1 Yes.2  62.9  65.2  D
0     100    Male  1.4  94.3  7.8  High School   No    No    No  75.3  79.2  C
1     101    Male  2.5  70.8  6.3  High School  Yes   Yes    No  51.2  74.5  C
2     102  Female  1.9  67.4  6.7    Bachelors  Yes   Yes   Yes  75.5  66.3  D
3     103  Female  6.0  69.7  6.8    Bachelors   No    No    No  65.3  89.5  B
4     104  Female  4.8  97.6  4.5  High School  Yes    No    No  60.9  92.7  A
..    ...     ...  ...   ...  ...          ...  ...   ...   ...   ...   ... ..
896   996    Male  2.8  75.4  8.2      Masters  Yes   Yes    No  60.5  70.7  C
897   997    Male  6.7  88.4  7.1          NaN   No   Yes    No  82.2  99.5  A
898   998  Female  2.6  84.5  8.0  High School  Yes   Yes   Yes  65.2  79.2  C
899   999  Female  4.6  85.3  8.1  High School   No    No   Yes  52.2  82.2  B
900  1000    Male  3.9  77.4  6.1      Masters  Yes    No    No  45.4  70.4  C

[901 rows x 12 columns]

In [10]:
csv_1.dtypes

student_id                      int64
gender                            str
study_time_hours              float64
attendance_percent                str
sleep_hours                   float64
parental_education                str
internet_access                   str
extracurricular_activities        str
part_time_job                     str
previous_grade                float64
final_exam_score              float64
final_grade                       str
dtype: object

In [14]:
csv_1=pd.read_csv("C:\\Users\\Local.Admin\\Desktop\\Python programs\\Pandas\\student_performance_dataset.csv",dtype={"attendance_percent":"float"})
csv_1

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [15]:
csv_1.dtypes

student_id                      int64
gender                            str
study_time_hours              float64
attendance_percent            float64
sleep_hours                   float64
parental_education                str
internet_access                   str
extracurricular_activities        str
part_time_job                     str
previous_grade                float64
final_exam_score              float64
final_grade                       str
dtype: object